export const PAGES = {
  MAIN: 'MAIN',
  SCHEDULE: 'SCHEDULE',
  LEAGUE_FILTER: 'LEAGUE_FILTER',
  PROFILE: 'PROFILE',
  BOOST_SELECT: 'BOOST_SELECT',
  FOLLOW_LEAGUE: 'FOLLOW_LEAGUE',
  FOLLOW_TEAM: 'FOLLOW_TEAM',
  FOLLOW_PLAYER: 'FOLLOW_PLAYER',
  RANK: 'RANK',
} as const

export type Page = (typeof PAGES)[keyof typeof PAGES]
