export const PAGES = {
  MAIN: 'MAIN',
  FOLLOW_LEAGUE: 'FOLLOW_LEAGUE',
  FOLLOW_TEAM: 'FOLLOW_TEAM',
  FOLLOW_PLAYER: 'FOLLOW_PLAYER',
  PROFILE: 'PROFILE',
  RANK: 'RANK',
  PURCHASE_LIST: 'PURCHASE_LIST',
} as const

export type Page = (typeof PAGES)[keyof typeof PAGES]
